mainSections   = ["post"]
rssFullContent = true
favicon        = "/img/avatar.png"

[footer]
    since = 2025
    customText = '<a href="/page/privacy/">개인정보 처리방침</a>'

[sidebar]
    emoji    = "🐢"
    subtitle = ""
    avatar   = "img/avatar.png"

[article]
    [article.license]
        enabled = false

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page = [{ type = "toc" }]

[comments]
    enabled = true
    provider = "giscus"

    [comments.giscus]
        repo = "rebugui/rebugui.github.io"
        repoID = "R_kgDORI9vfg"
        category = "General"
        categoryID = "DIC_kwDORI9vfs4C-epr"
        mapping = "pathname"
        strict = "0"
        lightTheme = "https://rebugui.github.io/giscus/light.css"
        darkTheme = "https://rebugui.github.io/giscus/dark.css"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "top"
        lang = "ko"
        loading = "lazy"

[colorScheme]
    toggle = true
    default = "auto"

[related]
    includeNewer = true
    threshold = 60
    toLower = false
    [[related.indices]]
        name = "tags"
        weight = 100
    [[related.indices]]
        name = "categories"
        weight = 200

[tableOfContents]
    endLevel = 4
    ordered = true
    startLevel = 2

[highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    tabWidth = 4
